
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.2.0
 * Query Engine version: 0c8ef2ce45c83248ab3df073180d5eda9e8be7a3
 */
Prisma.prismaVersion = {
  client: "7.2.0",
  engine: "0c8ef2ce45c83248ab3df073180d5eda9e8be7a3"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  role: 'role',
  stripeCustomerId: 'stripeCustomerId',
  credits: 'credits',
  planTier: 'planTier',
  createdAt: 'createdAt'
};

exports.Prisma.TransactionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  amount: 'amount',
  type: 'type',
  reference_id: 'reference_id',
  description: 'description',
  created_at: 'created_at'
};

exports.Prisma.ResumeScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  personalInfo: 'personalInfo',
  education: 'education',
  experience: 'experience',
  skills: 'skills',
  isDefault: 'isDefault',
  createdAt: 'createdAt'
};

exports.Prisma.CampaignScalarFieldEnum = {
  id: 'id',
  resumeId: 'resumeId',
  userId: 'userId',
  name: 'name',
  platform: 'platform',
  status: 'status',
  dailyLimit: 'dailyLimit',
  createdAt: 'createdAt'
};

exports.Prisma.CampaignLinkedinScalarFieldEnum = {
  id: 'id',
  campaignId: 'campaignId',
  searchTerms: 'searchTerms',
  locationTerm: 'locationTerm',
  sortBy: 'sortBy',
  datePosted: 'datePosted',
  expLevel: 'expLevel',
  jobType: 'jobType',
  remoteFilter: 'remoteFilter'
};

exports.Prisma.CampaignInfojobsScalarFieldEnum = {
  id: 'id',
  campaignId: 'campaignId',
  searchTerms: 'searchTerms',
  locationState: 'locationState',
  kmDeVoce: 'kmDeVoce',
  salaryFilter: 'salaryFilter',
  datePosted: 'datePosted',
  workModels: 'workModels',
  jobAreas: 'jobAreas',
  contractTypes: 'contractTypes',
  workSchedules: 'workSchedules',
  seniorityLevels: 'seniorityLevels',
  pcdTypes: 'pcdTypes'
};

exports.Prisma.JobApplicationScalarFieldEnum = {
  id: 'id',
  campaignId: 'campaignId',
  userId: 'userId',
  platform: 'platform',
  companyName: 'companyName',
  jobTitle: 'jobTitle',
  jobUrl: 'jobUrl',
  status: 'status',
  errorLog: 'errorLog',
  appliedAt: 'appliedAt',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.UserRole = exports.$Enums.UserRole = {
  admin: 'admin',
  user: 'user'
};

exports.TransactionType = exports.$Enums.TransactionType = {
  purchase: 'purchase',
  usage: 'usage',
  bonus: 'bonus',
  refund: 'refund'
};

exports.Platform = exports.$Enums.Platform = {
  linkedin: 'linkedin',
  infojobs: 'infojobs'
};

exports.LinkedinSort = exports.$Enums.LinkedinSort = {
  recent: 'recent',
  relevant: 'relevant'
};

exports.LinkedinDate = exports.$Enums.LinkedinDate = {
  any: 'any',
  past_month: 'past_month',
  past_week: 'past_week',
  past_24h: 'past_24h'
};

exports.LinkedinExp = exports.$Enums.LinkedinExp = {
  internship: 'internship',
  entry: 'entry',
  associate: 'associate',
  mid_senior: 'mid_senior',
  director: 'director',
  executive: 'executive'
};

exports.LinkedinJobType = exports.$Enums.LinkedinJobType = {
  full_time: 'full_time',
  part_time: 'part_time',
  contract: 'contract',
  temporary: 'temporary',
  volunteer: 'volunteer',
  internship: 'internship',
  other: 'other'
};

exports.LinkedinRemote = exports.$Enums.LinkedinRemote = {
  remote: 'remote',
  hybrid: 'hybrid',
  on_site: 'on_site'
};

exports.BrazilState = exports.$Enums.BrazilState = {
  acre: 'acre',
  alagoas: 'alagoas',
  amapa: 'amapa',
  amazonas: 'amazonas',
  bahia: 'bahia',
  ceara: 'ceara',
  distrito_federal: 'distrito_federal',
  espirito_santo: 'espirito_santo',
  goias: 'goias',
  maranhao: 'maranhao',
  mato_grosso: 'mato_grosso',
  mato_grosso_do_sul: 'mato_grosso_do_sul',
  minas_gerais: 'minas_gerais',
  para: 'para',
  paraiba: 'paraiba',
  parana: 'parana',
  pernambuco: 'pernambuco',
  piaui: 'piaui',
  rio_de_janeiro: 'rio_de_janeiro',
  rio_grande_do_norte: 'rio_grande_do_norte',
  rio_grande_do_sul: 'rio_grande_do_sul',
  rondonia: 'rondonia',
  roraima: 'roraima',
  santa_catarina: 'santa_catarina',
  sao_paulo: 'sao_paulo',
  sergipe: 'sergipe',
  tocantins: 'tocantins'
};

exports.IjRadius = exports.$Enums.IjRadius = {
  km_5: 'km_5',
  km_10: 'km_10',
  km_25: 'km_25',
  km_50: 'km_50',
  km_75: 'km_75',
  km_100: 'km_100'
};

exports.IjSalary = exports.$Enums.IjSalary = {
  brl_1000: 'brl_1000',
  brl_2000: 'brl_2000',
  brl_3000: 'brl_3000',
  brl_4000: 'brl_4000',
  brl_5000: 'brl_5000',
  brl_6000: 'brl_6000',
  brl_7000: 'brl_7000',
  brl_8000: 'brl_8000',
  brl_9000: 'brl_9000',
  brl_10000: 'brl_10000'
};

exports.IjDatePosted = exports.$Enums.IjDatePosted = {
  hoje: 'hoje',
  ultimos_3_dias: 'ultimos_3_dias',
  ultima_semana: 'ultima_semana',
  ultimos_15_dias: 'ultimos_15_dias',
  ultimo_mes: 'ultimo_mes'
};

exports.IjWorkModel = exports.$Enums.IjWorkModel = {
  presencial: 'presencial',
  home_office: 'home_office',
  hibrido: 'hibrido'
};

exports.IjJobArea = exports.$Enums.IjJobArea = {
  administracao: 'administracao',
  agricultura_pecuaria_veterinaria: 'agricultura_pecuaria_veterinaria',
  alimentacao_gastronomia: 'alimentacao_gastronomia',
  arquitetura_decoracao_design: 'arquitetura_decoracao_design',
  artes: 'artes',
  auditoria: 'auditoria',
  ciencias_pesquisa: 'ciencias_pesquisa',
  comercial_vendas: 'comercial_vendas',
  comercio_exterior: 'comercio_exterior',
  compras: 'compras',
  comunicacao_tv_cinema: 'comunicacao_tv_cinema',
  construcao_manutencao: 'construcao_manutencao',
  contabil_financas_economia: 'contabil_financas_economia',
  cultura_lazer_entretenimento: 'cultura_lazer_entretenimento',
  educacao_ensino_idiomas: 'educacao_ensino_idiomas',
  engenharia: 'engenharia',
  estetica: 'estetica',
  hotelaria_turismo: 'hotelaria_turismo',
  industrial_producao_fabrica: 'industrial_producao_fabrica',
  informatica_ti_telecomunicacoes: 'informatica_ti_telecomunicacoes',
  juridica: 'juridica',
  logistica: 'logistica',
  marketing: 'marketing',
  meio_ambiente_ecologia: 'meio_ambiente_ecologia',
  moda: 'moda',
  qualidade: 'qualidade',
  quimica_petroquimica: 'quimica_petroquimica',
  recursos_humanos: 'recursos_humanos',
  saude: 'saude',
  seguranca: 'seguranca',
  servico_social_comunitario: 'servico_social_comunitario',
  servicos_gerais: 'servicos_gerais',
  telemarketing: 'telemarketing',
  transportes: 'transportes'
};

exports.IjContract = exports.$Enums.IjContract = {
  clt: 'clt',
  autonomo: 'autonomo',
  pj: 'pj',
  cooperado: 'cooperado',
  jovem_aprendiz: 'jovem_aprendiz',
  estagio: 'estagio',
  temporario: 'temporario',
  trainee: 'trainee',
  outros: 'outros'
};

exports.IjSchedule = exports.$Enums.IjSchedule = {
  periodo_integral: 'periodo_integral',
  parcial_manha: 'parcial_manha',
  parcial_tarde: 'parcial_tarde',
  parcial_noite: 'parcial_noite',
  noturno: 'noturno'
};

exports.IjSeniority = exports.$Enums.IjSeniority = {
  estagiario: 'estagiario',
  operacional: 'operacional',
  auxiliar: 'auxiliar',
  assistente: 'assistente',
  trainee: 'trainee',
  tecnico: 'tecnico',
  analista: 'analista',
  encarregado: 'encarregado',
  supervisor: 'supervisor',
  consultor: 'consultor',
  especialista: 'especialista',
  coordenador: 'coordenador',
  gerente: 'gerente',
  diretor: 'diretor'
};

exports.IjPcd = exports.$Enums.IjPcd = {
  auditiva: 'auditiva',
  fisica: 'fisica',
  visual: 'visual',
  mental: 'mental',
  reabilitados: 'reabilitados',
  psicossocial: 'psicossocial',
  fala: 'fala',
  intelectual: 'intelectual',
  tea: 'tea'
};

exports.AppStatus = exports.$Enums.AppStatus = {
  pending: 'pending',
  applied: 'applied',
  failed: 'failed',
  skipped: 'skipped'
};

exports.Prisma.ModelName = {
  User: 'User',
  Transaction: 'Transaction',
  Resume: 'Resume',
  Campaign: 'Campaign',
  CampaignLinkedin: 'CampaignLinkedin',
  CampaignInfojobs: 'CampaignInfojobs',
  JobApplication: 'JobApplication'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
